version: '3.3'

services:
  app:
    image: node:22.12.0
    container_name: nextjs_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["sh", "-c", "npm install && npm run dev"]

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./cert:/etc/nginx/certs:ro # Папка для сертификатов (заготовка для будущего использования)
    depends_on:
      - app

networks:
  default:
    driver: bridge
