version: '3.3'

services:
  app:
    image: node:22.12.0
    container_name: nextjs_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npm run start"]
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cert:/etc/nginx/certs:ro
    depends_on:
      - app
    restart: always

networks:
  default:
    driver: bridge